---
- name: Playbook for preparations
  hosts: all

  roles: []

- name: Playbook for role testing
  hosts: all

  vars:
    operator_password: "$6$8w7/5t2r37WS$61H9A/0I68kgvEjTthmQzOOj3Yu2mKlhd8ehudSmqi4QHiKXvh5qtXPiYhKhVUdUI2MvlL8VAOhVDksB.gGZD0"

  roles:
    - role: ansible-operator
